### ISSUE TITLE
Is in progress ?

### ISSUE THREAD

**Issue by auriou** [tugberkugurlu/AspNetCore.Identity.Cassandra#5]
Hello, 

have you started something? 
There is another older library https://github.com/joshuadeanhall/AspNet.Identity.Cassandra. 
I start a Casssandra project with a wep api on .net core.
Otherwise I will adapt your lib mongo + the lib identity cassandra.

Thx

**Comment by tugberkugurlu** [comment]
yep, I have seen that but that's not for ASP.NET Core. I intend to continue on this but I am afraid there is no time frame on that 😞

**Comment by auriou** [comment]
I would share my work with you.

**Comment by tugberkugurlu** [comment]
> I would share my work with you.

That would be cool, feel free to have go and get a head start. Would love to see a PR for that 👍
